[[Gondolin Dark]]
  palette = "#080A0D:#FF7A77:#B9EC86:#FFE878:#83AEF8:#FF8DFF:#91D8CE:#D6DAE7:#505668:#FF7774:#B9FF6C:#FFF2A8:#71FEFF:#FFB3FF:#71FFDF:#ffffff"
  background_color = "#080A0D"
  foreground_color = "#D0D3DA"
  