# -----------------------------------------------------------------------------
# Gondolin Light
# Upstream: https://github.com/wunki/gondolin.nvim/blob/main/extras/alacritty/gondolin-light.toml
# URL: https://github.com/alacritty/alacritty
# -----------------------------------------------------------------------------

[colors.primary]
background = '#f4efe6'
foreground = '#5c6a72'

[colors.cursor]
cursor = '#46778d'
text = '#f4efe6'

[colors.selection]
background = '#e8e5d5'
foreground = '#829181'

[colors.normal]
black = '#5c6a72'
red = '#aa544d'
green = '#637827'
yellow = '#aa5f1b'
blue = '#46778d'
magenta = '#85647f'
cyan = '#477f5e'
white = '#f4efe6'

[colors.bright]
black = '#748278'
red = '#bb625b'
green = '#718735'
yellow = '#bd6e22'
blue = '#53879e'
magenta = '#95728e'
cyan = '#548f6c'
white = '#fffaf3'

[[colors.indexed_colors]]
index = 16
color = '#aa5f1b'

[[colors.indexed_colors]]
index = 17
color = '#aa544d'
