local color = require("gondolin.lib.color")

local M = {}

---@param opts GondolinConfig
---@param palette PaletteColors
---@return ThemeColors
M.get = function(opts, palette)
	---@type ThemeColors
	return {
		modes = {
			normal = palette.modeNormal,
			insert = palette.modeInsert,
			visual = palette.modeVisual,
			replace = palette.modeReplace,
			command = palette.modeCommand,
		},
		ui = {
			cursor = opts.cursor_color or palette.modeNormal,
			fg = palette.fg1,
			fg_dim = palette.fg4,
			fg_dimmer = palette.fg7,
			fg_dark = palette.fg8,
			fg_reverse = palette.bg2,
			bg_m4 = palette.bg0,
			bg_m3 = palette.bg1,
			bg_m2 = palette.bg2,
			bg_m1 = palette.bg3,
			bg_dim = palette.bg2,
			bg = palette.bg1,
			bg_p1 = palette.bg3,
			bg_p2 = palette.bg4,
			bg_gutter = opts.gutter and palette.bg3 or "none",
			bg_cursorline = palette.bg4,
			bg_cursorline_alt = palette.bg5,
			bg_search = palette.searchMatch,
			bg_visual = palette.selection,
			bg_statusline = palette.bg2,
			border = palette.border,
			header1 = palette.func,
			header2 = palette.constant,
			special = palette.accent,
			nontext = palette.fg8,
			whitespace = palette.fg8,
			win_separator = palette.border,
			indent = palette.bg5,
			indent_scope = palette.accent,
			picker = palette.error,
			yank = color(palette.warning):blend(palette.bg1, 0.5):to_hex(),
			yank_active = color(palette.warning):blend(palette.bg1, 0.25):to_hex(),
			mark = palette.info,
			scrollbar = palette.scrollThumb,
			tabline = {
				bg = palette.bg2,
				fg_selected = palette.fg1,
				bg_selected = palette.bg1,
				fg_inactive = palette.fg7,
				bg_inactive = palette.bg2,
				fg_alternate = palette.keyword,
				bg_alternate = palette.bg2,
				indicator = palette.accent,
			},
			pmenu = {
				fg = palette.fg1,
				fg_sel = "none", -- This is important to make highlights pass-through
				fg_border = palette.bg5,
				bg_border = palette.bg3,
				bg = palette.bg3,
				bg_sel = palette.bg5,
				bg_sbar = palette.bg3,
				bg_thumb = palette.fg8,
			},
			float = {
				fg = palette.fg2,
				bg = palette.bg2,
				fg_border = palette.border,
				bg_border = palette.bg2,
			},
			sidebar = {
				bg = palette.bg2,
			},
		},
		accent = {
			accent1 = palette.accent,
			accent2 = palette.constant,
			accent3 = palette.info,
			accent4 = palette.comment,
			accent5 = palette.error,
			invert = palette.bg4,
		},
		rainbow = {
			rainbow1 = palette.rainbow1,
			rainbow2 = palette.rainbow2,
			rainbow3 = palette.rainbow3,
			rainbow4 = palette.rainbow4,
			rainbow5 = palette.rainbow5,
			rainbow6 = palette.rainbow6,
			rainbow7 = palette.rainbow7,
		},
		syn = {
			attribute = palette.attribute,
			comment = palette.comment,
			constant = palette.constant,
			deprecated = palette.fg7,
			fun = palette.func,
			identifier = palette.variable,
			keyword = palette.keyword,
			member = palette.property,
			number = palette.constant,
			operator = palette.operator,
			parameter = palette.parameter,
			preproc = palette.keywordDirective,
			punct = palette.punctuation,
			regex = palette.stringRegex,
			statement = palette.keywordAlt,
			string = palette.string,
			symbol = palette.symbol,
			type = palette.type,
			variable = "none",
			special1 = palette.stringEscape,
			special2 = palette.tag,
			special3 = palette.hint,
			special4 = palette.tagDelimiter,
		},
		vcs = {
			added = palette.vcsAdded,
			added_light = color(palette.vcsAdded):blend(palette.bg1, 0.9):to_hex(),
			removed = palette.vcsDeleted,
			removed_light = color(palette.vcsDeleted):blend(palette.bg1, 0.9):to_hex(),
			changed = palette.vcsModified,
			changed_light = color(palette.vcsModified):blend(palette.bg1, 0.9):to_hex(),
		},
		diff = {
			add = palette.vcsAdded,
			add_light = color(palette.vcsAdded):blend(palette.bg1, 0.9):to_hex(),
			delete = palette.vcsDeleted,
			delete_light = color(palette.vcsDeleted):blend(palette.bg1, 0.9):to_hex(),
			change = palette.vcsModified,
			change_light = color(palette.vcsModified):blend(palette.bg1, 0.9):to_hex(),
			text = palette.info,
			text_light = color(palette.info):blend(palette.bg1, 0.9):to_hex(),
		},
		diag = {
			ok = palette.success,
			ok_light = color(palette.success):blend(palette.bg1, 0.92):to_hex(),
			error = palette.error,
			error_light = color(palette.error):blend(palette.bg1, 0.92):to_hex(),
			warning = palette.warning,
			warning_light = color(palette.warning):blend(palette.bg1, 0.92):to_hex(),
			info = palette.info,
			info_light = color(palette.info):blend(palette.bg1, 0.92):to_hex(),
			hint = palette.hint,
			hint_light = color(palette.hint):blend(palette.bg1, 0.92):to_hex(),
		},
		term = {
			black = palette.termBlack,
			red = palette.termRed,
			green = palette.termGreen,
			yellow = palette.termYellow,
			blue = palette.termBlue,
			magenta = palette.termMagenta,
			cyan = palette.termCyan,
			white = palette.termWhite,
			black_bright = palette.termBlackBright,
			red_bright = palette.termRedBright,
			green_bright = palette.termGreenBright,
			yellow_bright = palette.termYellowBright,
			blue_bright = palette.termBlueBright,
			magenta_bright = palette.termMagentaBright,
			cyan_bright = palette.termCyanBright,
			white_bright = palette.termWhiteBright,
			indexed1 = palette.constant,
			indexed2 = palette.error,
		},
	}
end

return M
