# -----------------------------------------------------------------------------
# Gondolin Light
# Upstream: https://github.com/wunki/gondolin.nvim/main/extras/foot/gondolin-light.ini
# URL: https://codeberg.org/dnkl/foot
# -----------------------------------------------------------------------------
[cursor]
color = 3f8d58 77593a

[colors]
background = f4efe6
foreground = 2f2417
selection-background = d7ccbe
selection-foreground = 786753
urls = 7d5bc4

search-box-no-match = 786753 c96369
search-box-match = 5778a5 786753

jump-labels = 77593a b77d2c

# Normal colors
regular0 = 2f2417
regular1 = b4545b
regular2 = 3f8d58
regular3 = 9f6c1f
regular4 = 4a6890
regular5 = 7d5bc4
regular6 = 356b7f
regular7 = f4efe6

# Bright colors
bright0 = 786753
bright1 = c96369
bright2 = 4d9d67
bright3 = b77d2c
bright4 = 5778a5
bright5 = 8f6dd6
bright6 = 427f95
bright7 = fffaf3

# Extended colors
16 = 9f6c1f
17 = b4545b
