# -----------------------------------------------------------------------------
# Gondolin Light
# Upstream: https://github.com/wunki/gondolin.nvim/blob/main/extras/foot/gondolin-light.ini
# URL: https://codeberg.org/dnkl/foot
# -----------------------------------------------------------------------------
[cursor]
color = 477f5e 46778d

[colors]
background = f4efe6
foreground = 5c6a72
selection-background = e8e5d5
selection-foreground = 829181
urls = 85647f

search-box-no-match = 748278 bb625b
search-box-match = 53879e 748278

jump-labels = 46778d bd6e22

# Normal colors
regular0 = 5c6a72
regular1 = aa544d
regular2 = 637827
regular3 = aa5f1b
regular4 = 46778d
regular5 = 85647f
regular6 = 477f5e
regular7 = f4efe6

# Bright colors
bright0 = 748278
bright1 = bb625b
bright2 = 718735
bright3 = bd6e22
bright4 = 53879e
bright5 = 95728e
bright6 = 548f6c
bright7 = fffaf3

# Extended colors
16 = aa5f1b
17 = aa544d
