# -----------------------------------------------------------------------------
# Gondolin Dark
# Upstream: https://github.com/wunki/gondolin.nvim/blob/main/extras/foot/gondolin-dark.ini
# URL: https://codeberg.org/dnkl/foot
# -----------------------------------------------------------------------------
[cursor]
color = B9EC86 83AEF8

[colors]
background = 080A0D
foreground = D0D3DA
selection-background = 1a1d23
selection-foreground = A2AEC0
urls = 958BCC

search-box-no-match = 505668 FF7774
search-box-match = 71FEFF 505668

jump-labels = 83AEF8 FFE878

# Normal colors
regular0 = 080A0D
regular1 = FF7A77
regular2 = B9EC86
regular3 = FFE878
regular4 = 83AEF8
regular5 = FF8DFF
regular6 = 83AEF8
regular7 = D6DAE7

# Bright colors
bright0 = 505668
bright1 = FF7774
bright2 = B9FF6C
bright3 = FFE878
bright4 = 71FEFF
bright5 = FF8DFF
bright6 = 71FFDF
bright7 = ffffff

# Extended colors
16 = FFBE78
17 = FF7A77
