local util = require("gondolin.lib.util")

local M = {}

--- @param colors ThemeColors
function M.generate(colors)
	return util.template(
		[[
{
  "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
  "name": "${_style_name}",
  "author": "Petar Radosevic",
  "themes": [
    {
      "name": "${_style_name}",
      "appearance": "${_theme}",
      "style": {
        "border": "${ui.border}",
        "border.variant": "${ui.win_separator}",
        "border.focused": "${modes.normal}",
        "border.selected": "${ui.bg_p2}",
        "border.transparent": "#00000000",
        "border.disabled": "${ui.bg_m2}",

        "background": "${ui.bg}",
        "surface.background": "${ui.bg_m2}",
        "elevated_surface.background": "${ui.bg_m1}",

        "editor.foreground": "${ui.fg}",
        "editor.background": "${ui.bg}",
        "editor.gutter.background": "${ui.bg}",
        "editor.active_line.background": "${ui.bg_cursorline}",
        "editor.highlighted_line.background": "${ui.bg_cursorline_alt}",
        "editor.subheader.background": "${ui.bg_m1}",
        "editor.active_line_number": "${ui.fg_dim}",
        "editor.line_number": "${ui.line_nr}",
        "editor.invisible": "${ui.nontext}",
        "editor.wrap_guide": "${ui.indent}",
        "editor.active_wrap_guide": "${ui.indent_scope}",
        "editor.document_highlight.read_background": "${ui.bg_visual}66",
        "editor.document_highlight.write_background": "${ui.bg_visual}99",

        "panel.background": "${ui.bg_m2}",
        "panel.focused_border": "${modes.normal}",
        "status_bar.background": "${ui.bg_statusline}",
        "title_bar.background": "${ui.bg_m2}",
        "toolbar.background": "${ui.bg}",
        "pane.focused_border": "${modes.normal}",

        "tab_bar.background": "${ui.tabline.bg}",
        "tab.inactive_background": "${ui.tabline.bg_inactive}",
        "tab.active_background": "${ui.tabline.bg_selected}",

        "element.background": "${ui.bg_m1}",
        "element.hover": "${ui.bg_p2}",
        "element.active": "${ui.bg_p1}",
        "element.selected": "${ui.bg_p2}",
        "element.disabled": "${ui.bg_m2}",

        "drop_target.background": "${ui.bg_visual}",
        "ghost_element.background": "#00000000",
        "ghost_element.disabled": "#00000000",
        "ghost_element.hover": "${ui.bg_p1}",
        "ghost_element.active": "${ui.bg_p2}",
        "ghost_element.selected": "${ui.bg_p2}",

        "text": "${ui.fg}",
        "text.muted": "${ui.fg_dim}",
        "text.placeholder": "${ui.fg_dimmer}",
        "text.disabled": "${ui.fg_dimmer}",
        "text.accent": "${modes.normal}",

        "icon": "${ui.fg}",
        "icon.muted": "${ui.fg_dim}",
        "icon.disabled": "${ui.fg_dimmer}",
        "icon.placeholder": "${ui.fg_dimmer}",
        "icon.accent": "${modes.normal}",

        "scrollbar_thumb.background": "${ui.scrollbar}44",
        "scrollbar.thumb.hover_background": "${ui.scrollbar}88",
        "scrollbar.thumb.border": "#00000000",
        "scrollbar.track.background": "#00000000",
        "scrollbar.track.border": "#00000000",

        "hint": "${diag.hint}",
        "hint.background": "${diag.hint_light}",
        "hint.border": "${diag.hint}",
        "error": "${diag.error}",
        "error.background": "${diag.error_light}",
        "error.border": "${diag.error}",
        "info": "${diag.info}",
        "info.background": "${diag.info_light}",
        "info.border": "${diag.info}",
        "warning": "${diag.warning}",
        "warning.background": "${diag.warning_light}",
        "warning.border": "${diag.warning}",
        "success": "${diag.ok}",
        "success.background": "${diag.ok_light}",
        "success.border": "${diag.ok}",

        "conflict": "${diag.warning}",
        "conflict.background": "${diff.change_light}",
        "conflict.border": "${diag.warning}",
        "created": "${vcs.added}",
        "created.background": "${vcs.added_light}",
        "created.border": "${vcs.added}",
        "deleted": "${vcs.removed}",
        "deleted.background": "${vcs.removed_light}",
        "deleted.border": "${vcs.removed}",
        "modified": "${vcs.changed}",
        "modified.background": "${vcs.changed_light}",
        "modified.border": "${vcs.changed}",
        "renamed": "${vcs.changed}",
        "renamed.background": "${vcs.changed_light}",
        "renamed.border": "${vcs.changed}",

        "hidden": "${ui.fg_dimmer}",
        "hidden.background": "${ui.bg_m2}",
        "hidden.border": "${ui.border}",
        "ignored": "${ui.fg_dimmer}",
        "ignored.background": "${ui.bg_m2}",
        "ignored.border": "${ui.border}",
        "predictive": "${ui.fg_dimmer}",
        "predictive.background": "${ui.bg_m2}",
        "predictive.border": "${ui.border}",
        "unreachable": "${ui.fg_dimmer}",
        "unreachable.background": "${ui.bg_m2}",
        "unreachable.border": "${ui.border}",

        "search.match_background": "${ui.bg_search}",
        "link_text.hover": "${modes.normal}",

        "terminal.background": "${ui.bg}",
        "terminal.foreground": "${ui.fg}",
        "terminal.bright_foreground": "${term.white_bright}",
        "terminal.dim_foreground": "${ui.fg_dimmer}",
        "terminal.ansi.black": "${term.black}",
        "terminal.ansi.red": "${term.red}",
        "terminal.ansi.green": "${term.green}",
        "terminal.ansi.yellow": "${term.yellow}",
        "terminal.ansi.blue": "${term.blue}",
        "terminal.ansi.magenta": "${term.magenta}",
        "terminal.ansi.cyan": "${term.cyan}",
        "terminal.ansi.white": "${term.white}",
        "terminal.ansi.bright_black": "${term.black_bright}",
        "terminal.ansi.bright_red": "${term.red_bright}",
        "terminal.ansi.bright_green": "${term.green_bright}",
        "terminal.ansi.bright_yellow": "${term.yellow_bright}",
        "terminal.ansi.bright_blue": "${term.blue_bright}",
        "terminal.ansi.bright_magenta": "${term.magenta_bright}",
        "terminal.ansi.bright_cyan": "${term.cyan_bright}",
        "terminal.ansi.bright_white": "${term.white_bright}",

        "syntax": {
          "variable": { "color": "${syn.identifier}" },
          "variable.builtin": { "color": "${syn.special1}" },
          "variable.parameter": { "color": "${syn.parameter}" },
          "variable.member": { "color": "${syn.member}" },
          "variable.special": { "color": "${syn.special1}" },

          "constant": { "color": "${syn.constant}" },
          "constant.builtin": { "color": "${syn.constant}" },
          "constant.macro": { "color": "${syn.constant}" },
          "boolean": { "color": "${syn.constant}" },
          "number": { "color": "${syn.number}" },
          "number.float": { "color": "${syn.number}" },

          "string": { "color": "${syn.string}" },
          "string.documentation": { "color": "${syn.string}", "font_style": "italic" },
          "string.regexp": { "color": "${syn.regex}" },
          "string.escape": { "color": "${syn.special1}" },
          "string.special": { "color": "${syn.symbol}" },
          "string.special.symbol": { "color": "${syn.symbol}" },
          "string.special.url": { "color": "${modes.normal}", "font_style": "italic" },
          "character": { "color": "${syn.string}" },
          "character.special": { "color": "${syn.special1}" },

          "type": { "color": "${syn.type}" },
          "type.builtin": { "color": "${syn.type}" },
          "type.definition": { "color": "${syn.type}" },
          "type.interface": { "color": "${syn.type}" },
          "type.super": { "color": "${syn.type}" },

          "function": { "color": "${syn.fun}" },
          "function.builtin": { "color": "${syn.fun}" },
          "function.call": { "color": "${syn.fun}" },
          "function.macro": { "color": "${syn.fun}" },
          "function.method": { "color": "${syn.fun}" },
          "function.method.call": { "color": "${syn.fun}" },
          "function.decorator": { "color": "${syn.attribute}" },

          "keyword": { "color": "${syn.keyword}" },
          "keyword.modifier": { "color": "${syn.statement}" },
          "keyword.type": { "color": "${syn.statement}" },
          "keyword.coroutine": { "color": "${syn.statement}" },
          "keyword.function": { "color": "${syn.statement}" },
          "keyword.operator": { "color": "${syn.statement}" },
          "keyword.import": { "color": "${syn.statement}" },
          "keyword.repeat": { "color": "${syn.statement}" },
          "keyword.return": { "color": "${syn.statement}" },
          "keyword.exception": { "color": "${syn.statement}" },
          "keyword.conditional": { "color": "${syn.statement}" },
          "keyword.directive": { "color": "${syn.preproc}" },
          "keyword.export": { "color": "${syn.preproc}" },

          "punctuation": { "color": "${syn.punct}" },
          "punctuation.delimiter": { "color": "${syn.punct}" },
          "punctuation.bracket": { "color": "${syn.punct}" },
          "punctuation.special": { "color": "${syn.special4}" },
          "operator": { "color": "${syn.operator}" },

          "comment": { "color": "${syn.comment}", "font_style": "italic" },
          "comment.doc": { "color": "${ui.fg_dim}", "font_style": "italic" },
          "comment.documentation": { "color": "${ui.fg_dim}", "font_style": "italic" },
          "comment.error": { "color": "${diag.error}", "font_style": "italic" },
          "comment.warning": { "color": "${diag.warning}", "font_style": "italic" },
          "comment.hint": { "color": "${diag.hint}", "font_style": "italic" },
          "comment.todo": { "color": "${syn.special1}", "font_style": "italic" },
          "comment.note": { "color": "${diag.info}", "font_style": "italic" },

          "tag": { "color": "${syn.special2}" },
          "tag.attribute": { "color": "${syn.attribute}", "font_style": "italic" },
          "tag.delimiter": { "color": "${syn.punct}" },
          "tag.doctype": { "color": "${syn.preproc}" },

          "diff.plus": { "color": "${vcs.added}" },
          "diff.minus": { "color": "${vcs.removed}" },

          "text": { "color": "${ui.fg}" },
          "text.literal": { "color": "${syn.string}" },
          "emphasis.strong": { "color": "${syn.special1}", "font_weight": 700 },
          "emphasis": { "color": "${syn.special1}", "font_style": "italic" },
          "title": { "color": "${ui.header1}", "font_weight": 700 },
          "link_text": { "color": "${ui.header2}" },
          "link_uri": { "color": "${modes.normal}", "font_style": "italic" },

          "attribute": { "color": "${syn.attribute}" },
          "property": { "color": "${syn.member}" },
          "constructor": { "color": "${syn.fun}" },
          "parameter": { "color": "${syn.parameter}" },
          "field": { "color": "${syn.member}" },
          "namespace": { "color": "${syn.type}", "font_style": "italic" },
          "module": { "color": "${syn.type}" },
          "label": { "color": "${syn.special3}" },
          "symbol": { "color": "${syn.symbol}" },
          "embedded": { "color": "${syn.special1}" },
          "enum": { "color": "${syn.type}" },
          "hint": { "color": "${ui.fg_dimmer}", "font_style": "italic" },
          "parent": { "color": "${syn.special4}" },
          "predictive": { "color": "${ui.fg_dimmer}", "font_style": "italic" }
        }
      }
    }
  ]
}
]],
		colors
	)
end

return M
