# Gondolin Light - tmux theme
# https://github.com/wunki/gondolin.nvim/main/extras/tmux/gondolin-light.conf

color_bg0="#d8c8b3"
color_bg1="#e4d6c6"
color_bg2="#eee4d6"
color_bg3="#eee4d6"
color_fg0="#2f2417"
color_fg1="#786753"
color_red="#b4545b"
color_orange="#9f6c1f"
color_yellow="#9f6c1f"
color_green="#3f8d58"
color_blue="#77593a"
color_purple="#7b5a35"
color_grey0="#b39c80"
color_grey1="#9b8367"

# by default window names will just be their index
set-option -g automatic-rename              on
set-option -g automatic-rename-format       "#I"

# set to 12 for a 12-hour clock
set-option -g clock-mode-style              24
set-option -g clock-mode-colour             "$color_green"

# NOTE: color variable expansion only works in double quotes
set-option -g status-fg                     "$color_fg0"
set-option -g status-bg                     "$color_bg1"
set-option -g copy-mode-current-match-style "fg=$color_bg0,bg=$color_yellow"
set-option -g copy-mode-match-style         "fg=$color_bg0,bg=$color_blue"
set-option -g menu-selected-style           "fg=$color_bg0,bg=$color_blue"
set-option -g menu-style                    "fg=$color_fg0,bg=$color_bg1"
set-option -g message-style                 "bg=$color_yellow,fg=$color_bg0"
set-option -g message-command-style         "bg=$color_bg2,fg=$color_fg0"
set-option -g mode-style                    "bg=$color_bg2,fg=$color_fg0"
set-option -g pane-active-border-style      "fg=$color_blue"
set-option -g pane-border-lines             "heavy"
set-option -g pane-border-style             "fg=$color_bg3"
set-option -g popup-border-lines            "rounded"
set-option -g status-right-style            "fg=$color_fg1"
set-option -g window-status-current-style   "fg=$color_blue"
set-option -g window-status-style           "fg=$color_fg1"
set -g default-terminal "${TERM}"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# display the window index number or index-number:name if has a name
set-option -g window-status-separator      ''
set-option -g window-status-format         '#[fg=#786753]#[bg=#e4d6c6] #{?#{==:#W, },#I,#I #[fg=#786753]#[bg=#eee4d6] #W }'
set-option -g window-status-current-format '#[fg=#2f2417]#[bg=#d8c8b3]#[bold] #{?#{==:#W, },#I,#I #[fg=#77593a]#[bg=#eee4d6] #W }'

# status right will show the current session name if there is more than one session
set-option -g status-right                 '#{?#{>:#{server_sessions},1}, #[fg=#9f6c1f]◆ #[fg=#2f2417]#{session_name} ,}'
set-option -g status-left                  ''
