# -----------------------------------------------------------------------------
# Gondolin Light
# Upstream: https://github.com/wunki/gondolin.nvim/blob/main/extras/kitty/gondolin-light.conf
# URL: https://sw.kovidgoyal.net/kitty/conf.html
# -----------------------------------------------------------------------------

background #f4efe6
foreground #5c6a72
selection_background #e8e5d5
selection_foreground #829181
url_color #85647f
cursor #46778d
cursor_text_color #f4efe6

# Tabs
active_tab_background #f4efe6
active_tab_foreground #46778d
inactive_tab_background #eee4d6
inactive_tab_foreground #829181
tab_bar_background #eee4d6

# normal
color0 #5c6a72
color1 #aa544d
color2 #637827
color3 #aa5f1b
color4 #46778d
color5 #85647f
color6 #477f5e
color7 #f4efe6

# bright
color8  #748278
color9  #bb625b
color10 #718735
color11 #bd6e22
color12 #53879e
color13 #95728e
color14 #548f6c
color15 #fffaf3

# extended colors
color16 #aa5f1b
color17 #aa544d
