# -----------------------------------------------------------------------------
# Gondolin Dark
# Upstream: https://github.com/wunki/gondolin.nvim/blob/main/extras/kitty/gondolin-dark.conf
# URL: https://sw.kovidgoyal.net/kitty/conf.html
# -----------------------------------------------------------------------------

background #080A0D
foreground #D0D3DA
selection_background #1a1d23
selection_foreground #A2AEC0
url_color #958BCC
cursor #83AEF8
cursor_text_color #080A0D

# Tabs
active_tab_background #080A0D
active_tab_foreground #83AEF8
inactive_tab_background #101318
inactive_tab_foreground #A2AEC0
tab_bar_background #101318

# normal
color0 #080A0D
color1 #FF7A77
color2 #B9EC86
color3 #FFE878
color4 #83AEF8
color5 #FF8DFF
color6 #83AEF8
color7 #D6DAE7

# bright
color8  #505668
color9  #FF7774
color10 #B9FF6C
color11 #FFE878
color12 #71FEFF
color13 #FF8DFF
color14 #71FFDF
color15 #ffffff

# extended colors
color16 #FFBE78
color17 #FF7A77
