# -----------------------------------------------------------------------------
# Gondolin Light
# Upstream: https://github.com/wunki/gondolin.nvim/blob/main/extras/termux/gondolin-light.properties
# URL: https://termux.dev/
# -----------------------------------------------------------------------------
background: #f4efe6
foreground: #5c6a72

# Normal colors
color0:  #5c6a72
color1:  #aa544d
color2:  #637827
color3:  #aa5f1b
color4:  #46778d
color5:  #85647f
color6:  #477f5e
color7:  #f4efe6

# Bright colors
color8:  #748278
color9:  #bb625b
color10: #718735
color11: #bd6e22
color12: #53879e
color13: #95728e
color14: #548f6c
color15: #fffaf3

# Extended colors
color16: #aa5f1b
color17: #aa544d
