# -----------------------------------------------------------------------------
# Gondolin Dark
# Upstream: https://github.com/wunki/gondolin.nvim/blob/main/extras/termux/gondolin-dark.properties
# URL: https://termux.dev/
# -----------------------------------------------------------------------------
background: #080A0D
foreground: #D0D3DA

# Normal colors
color0:  #080A0D
color1:  #FF7A77
color2:  #B9EC86
color3:  #FFE878
color4:  #83AEF8
color5:  #FF8DFF
color6:  #83AEF8
color7:  #D6DAE7

# Bright colors
color8:  #505668
color9:  #FF7774
color10: #B9FF6C
color11: #FFE878
color12: #71FEFF
color13: #FF8DFF
color14: #71FFDF
color15: #ffffff

# Extended colors
color16: #FFBE78
color17: #FF7A77
